import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const args = process.argv.slice(2);
const appName = args[0];

if (!appName) {
    console.error('❌ Usage: npx tsx scripts/scaffold-new-app.ts <app-name>');
    process.exit(1);
}

const rootDir = process.cwd();
const appsDir = path.join(rootDir, 'apps');
const targetDir = path.join(appsDir, appName);

if (fs.existsSync(targetDir)) {
    console.error(`❌ Error: App directory '${targetDir}' already exists.`);
    process.exit(1);
}

console.log(`🚀 Scaffolding new app: ${appName} in apps/${appName}...`);

// 1. Create Directories
const dirs = [
    targetDir,
    path.join(targetDir, 'src'),
    path.join(targetDir, 'src/app'),
    path.join(targetDir, 'public'),
];

dirs.forEach(dir => {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// 2. Create package.json
const packageJson = {
    "name": appName,
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "dev": `node ../../scripts/run-with-secrets.js ${appName} next dev`,
        "dev:standalone": "next dev",
        "build": "next build",
        "start": `node ../../scripts/run-with-secrets.js ${appName} next start`,
        "start:standalone": "next start",
        "test": "vitest run",
        "lint": "eslint"
    },
    "dependencies": {
        "@alpha/ui": "*",
        "@alpha/sdk": "*",
        "@modelcontextprotocol/sdk": "^1.26.0",
        "next": "16.1.6",
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
        "zod": "^4.3.6"
    },
    "devDependencies": {
        "@tailwindcss/postcss": "^4",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "eslint": "^9",
        "eslint-config-next": "16.1.6",
        "tailwindcss": "^4",
        "typescript": "^5",
        "vitest": "^4.0.18"
    }
};

fs.writeFileSync(path.join(targetDir, 'package.json'), JSON.stringify(packageJson, null, 2));

// 3. Create tsconfig.json
const tsConfig = {
    "compilerOptions": {
        "target": "ES2017",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "bundler",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "react-jsx",
        "incremental": true,
        "plugins": [{ "name": "next" }],
        "paths": { "@/*": ["./src/*"] }
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    "exclude": ["node_modules"]
};

fs.writeFileSync(path.join(targetDir, 'tsconfig.json'), JSON.stringify(tsConfig, null, 2));

// 4. Create next.config.ts
const nextConfig = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  transpilePackages: ["@alpha/ui"],
};

export default nextConfig;
`;
fs.writeFileSync(path.join(targetDir, 'next.config.ts'), nextConfig);

// 5. Create tailwind.config.ts
const tailwindConfig = `import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "../../packages/ui/src/**/*.{ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
            },
        },
    },
    plugins: [],
};
export default config;
`;
fs.writeFileSync(path.join(targetDir, 'tailwind.config.ts'), tailwindConfig);

// 6. Create postcss.config.mjs
const postcssConfig = `const config = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
export default config;
`;
fs.writeFileSync(path.join(targetDir, 'postcss.config.mjs'), postcssConfig);

// 7. Create globals.css
const globalsCss = `@import "tailwindcss";
@import "@alpha/ui/alpha-theme.css";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}
`;
fs.writeFileSync(path.join(targetDir, 'src/app/globals.css'), globalsCss);

// 8. Create layout.tsx
const layoutTsx = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${appName} | Alpha Ecosystem",
  description: "Generated by Alpha Scaffolder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
`;
fs.writeFileSync(path.join(targetDir, 'src/app/layout.tsx'), layoutTsx);

// 9. Create page.tsx
const pageTsx = `import { Button } from "@alpha/ui";

export default function Home() {
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <h1 className="text-4xl font-bold">${appName}</h1>
        <p className="text-lg">Generated standard Alpha app.</p>
        <div className="flex gap-4">
            <Button variant="default">Primary Action</Button>
            <Button variant="outline">Secondary Action</Button>
        </div>
      </main>
    </div>
  );
}
`;
fs.writeFileSync(path.join(targetDir, 'src/app/page.tsx'), pageTsx);

// 10. .env.local.example
fs.writeFileSync(path.join(targetDir, '.env.local.example'), `# Standalone Mode Credentials
ALPHA_MASTER_KEY=
`);

console.log('✅ Scaffolding complete!');
console.log('');
console.log('👉 Next Steps:');
console.log('1. Run npm install from the root.');
console.log(`2. cd apps/${appName}`);
console.log('3. npm run dev');
